### ISSUE TITLE
P2 Layout: start writing about the specifics of fonts/color scheme/body width/links (internal/exernal), navbar style/footer/border/logo (as seen at https://folk.idi.ntnu.no/michailg/IT2805/exampleproject/p2_designexample.html)

### ISSUE THREAD

**Issue by martivj** [michaelbrusegard/NiclasNordlundPhotography#9]

**Comment by ottohf** [comment]
fonts
There are two fonts on the website, and both are based on Niclas' logo. The first is a font called "caveat cursive" with a handwritten look, mainly used for the different categories in the navbar. The font resembles Niclas' signature.

The second font is Noto Sans Mono, weight 200. The font resembles the one used in the word "photography" in the logo. This is a sans serif font and the main font on the site. 

color scheme
The color scheme is oriented towards putting emphasis on the photos on the site. 
Navbar: #add8e6


body width
1000px

links (internal/external)
All links in the navbar will link to internal web pages. The link to his instagram and facebook accounts will link to external pages. 



navbar style
The navbar will a normal horizontal bar at the top for desktop users and a hamburger menu which can be expanded and closed on phones. It will contain internal links to the different photo categories.


footer
The footer will contain contact information and links to Niclas' Instagram and Facebook accounts. It has the same height as the navbar and is only visible when the user has scrolled to the bottom. 


border
?



logo
The website logo is Niclas' signature and the word "photography", and acts as a "home" button on the website. When the signature is clicked, the user is directed to the main website. The logo will be in the top left corner.
